# site settings
title: Sahil
subtitle: Saboo
email: sahilsaboo98@gmail.com
description: A passionate product manager, lifelong learner, and oxford comma enthusiast. </br> This is my personal space where I share my thoughts, musings, book reviews, and more.
baseurl: # the subpath of your site, e.g. /blog
url: "https://sahilsaboo.github.io/" # the base hostname & protocol for your site
author: Sahil Saboo
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/sahilsaboo
  GitLab:
  Instagram: https://www.instagram.com/sahilsaboo/
  LinkedIn: https://www.linkedin.com/in/sahil-saboo/
  Twitter: https://x.com/sahilsaboo
  Facebook:
  email: mailto:sahilsaboo98@gmail.com
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
